### PR TITLE
Issue #146: remove NotNull constraint

### PR DESCRIPTION
**Pull request by Francois-Werbrouck**
Ref #146

### CODE REVIEW

**Review by k-allagbe — COMMENTED** [review]
There are still a lot of NOT NULL fields.

For instance:
```sql
    CREATE TABLE "fertiscan_0.0.12"."organization_information" (
        "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
        "name" text NOT NULL,
        "website" text,
        "phone_number" text,
        "location_id" uuid REFERENCES "fertiscan_0.0.12".location(id),
        "edited" boolean DEFAULT false
    );

```

It could happen that name is not found by the pipeline.

What do you think of not imposing the NOT NULL constraint anywhere for now?

Also, don't forget to update/add tests.

**Comment by Francois-Werbrouck** [comment]
> What do you think of not imposing the NOT NULL constraint anywhere for now?
Already done

> Also, don't forget to update/add tests.
I will add some, next time they should be done in the PR where we changed the Null Constraint. Even if a PR is deemed urgent.
I've patch most (if not all) places where an object strictly composed of null field was about to be written.

**Review by k-allagbe — COMMENTED** [review]
Should we write a test for `new_inspection_with_label_info` with 

```json
{
  "company_name": null,
  "company_address": null,
  "company_website": null,
  "company_phone_number": null,
  "manufacturer_name": null,
  "manufacturer_address": null,
  "manufacturer_website": null,
  "manufacturer_phone_number": null,
  "fertiliser_name": null,
  "registration_number": null,
  "lot_number": null,
  "weight": [],
  "density": null,
  "volume": null,
  "npk": null,
  "warranty": null,
  "cautions_en": [],
  "instructions_en": [],
  "micronutrients_en": [],
  "ingredients_en": [],
  "specifications_en": [],
  "first_aid_en": [],
  "cautions_fr": [],
  "instructions_fr": [],
  "micronutrients_fr": [],
  "ingredients_fr": [],
  "specifications_fr": [],
  "first_aid_fr": [],
  "guaranteed_analysis": []
}
```
?

I think that would help make sure that the modifications all come together nicely.

**Comment by Francois-Werbrouck** [comment]
> Should we write a test for `new_inspection_with_label_info` with
> 
> ```json
> {
>   "company_name": null,
>   "company_address": null,
>   "company_website": null,
>   "company_phone_number": null,
>   "manufacturer_name": null,
>   "manufacturer_address": null,
>   "manufacturer_website": null,
>   "manufacturer_phone_number": null,
>   "fertiliser_name": null,
>   "registration_number": null,
>   "lot_number": null,
>   "weight": [],
>   "density": null,
>   "volume": null,
>   "npk": null,
>   "warranty": null,
>   "cautions_en": [],
>   "instructions_en": [],
>   "micronutrients_en": [],
>   "ingredients_en": [],
>   "specifications_en": [],
>   "first_aid_en": [],
>   "cautions_fr": [],
>   "instructions_fr": [],
>   "micronutrients_fr": [],
>   "ingredients_fr": [],
>   "specifications_fr": [],
>   "first_aid_fr": [],
>   "guaranteed_analysis": []
> }
> ```
> 
> ?
> 
> I think that would help make sure that the modifications all come together nicely.



> Should we write a test for `new_inspection_with_label_info` with
> 
> ```json
> {
>   "company_name": null,
>   "company_address": null,
>   "company_website": null,
>   "company_phone_number": null,
>   "manufacturer_name": null,
>   "manufacturer_address": null,
>   "manufacturer_website": null,
>   "manufacturer_phone_number": null,
>   "fertiliser_name": null,
>   "registration_number": null,
>   "lot_number": null,
>   "weight": [],
>   "density": null,
>   "volume": null,
>   "npk": null,
>   "warranty": null,
>   "cautions_en": [],
>   "instructions_en": [],
>   "micronutrients_en": [],
>   "ingredients_en": [],
>   "specifications_en": [],
>   "first_aid_en": [],
>   "cautions_fr": [],
>   "instructions_fr": [],
>   "micronutrients_fr": [],
>   "ingredients_fr": [],
>   "specifications_fr": [],
>   "first_aid_fr": [],
>   "guaranteed_analysis": []
> }
> ```
> 
> ?
> 
> I think that would help make sure that the modifications all come together nicely.

python -m unittest tests.fertiscan.test_datastore.TestDatastore.test_register_analysis_empty

**Review by k-allagbe — DISMISSED** [review]

**Comment by k-allagbe** [comment]
Are the tests being executed?

image

Also, don't forget to rebase on main.

**Pull request merged**
