### PR TITLE
Issue #135: refer Bytebase doc to dev-rel-docs

### PR DESCRIPTION
**Pull request by Francois-Werbrouck**
ref #135

### CODE REVIEW

**Comment by k-allagbe** [comment]
I suggest we get bytebase approved before merging this.

**Comment by Francois-Werbrouck** [comment]
It was already approved by @nmeraihi in the past (Which was the reason behind this PR that got lost through more urgent matters) and we are already self hosting our own instance of the tool.

**Review by k-allagbe — APPROVED** [review]
Please, fix the markdown-check errors. If we could get rid of this it would be great.

**Comment by Francois-Werbrouck** [comment]
>Please, fix the markdown-check errors.

I did, however, 
image

This will keep on happening until [#135 on dev-rel-docs](https://github.com/ai-cfia/dev-rel-docs/pull/136) is merged. The rest of the tests are passing!

**Review by k-allagbe — APPROVED** [review]

**Pull request merged**
