### PR TITLE
New folder structure

### PR DESCRIPTION
**Pull request by SonOfLope**
ref : 
- #112 
- https://github.com/ai-cfia/nachet-backend/issues/109

### CODE REVIEW

**Comment by Francois-Werbrouck** [comment]
# TODO🚀 
**Datastore -> Nachet 🌱 **
📦 `bin/`
- `db-mock-seeds-population.py`
- `deployment_mass_import.py`
- `ml-import.py`

📦 `blob/azure_storage_api/`
- `init.create_dev_container_folder()`
  - This one might be tricky since its only one function and could be resolved in a separate issue if we really want to move it.

📦 `tests/`
- All of it need to be moved; it is a test file for ` deployment_mass_import.py`

The structure for `db/` needs to be replicated in both `nachet/` and `fertiscan/`. There needs to be:
- `metadata/`
- `bytebase/`
  - This one already has a file with all fertiscan data and the rest is all Nachet's
  - This one can be deleted afterward, since it should be empty.
- `queries/`

The project's specific object file need to be moved:
| Nachet 🌱  | FertiScan 👨🏻‍🌾 |
| --------| -------|
| inference | inspection|
| machine_learning | ingredient |
| seed | label |
| picture (only the metadata file, explanation bellow)| metric |
| | nutrients|
| | organization | 
| | specification|
| | sub_label l

## Special attention:
📦 `datastore/db/metadata/validator/init`
- This file is used in (almost every) tests for its function `is_valid_uuid()`. However it also has some model structure that might be used in a few Nachet tests. 

📦 `datastore/db/metadata/template/*`
- I'm not sure if this is still used in Nachet... 😮‍💨

📦 `datastore/db/queries/user/` 
- I'm not sure what to do with this one. Both project use it since they both use the same user structure. Maybe it should stay in the datastore for now and both project will use it from there?

📦 `datastore/db/queries/picture/` & `datastore/db/queries/picture_set/`
- Just like the user, both project use the same DB structure for their project for the picture & picture_set entity. The query module should stay in datastore maybe?
- The 

📦 `doc`
- Do we want to make a doc directory for each project?

**Review by k-allagbe — APPROVED** [review]

**Review by Francois-Werbrouck — APPROVED** [review]
LGTM

**Comment by k-allagbe** [comment]
I'm curious, how does nachet-backend or fertiscan-backend install the package now that this has been merged? What happens if they are redeployed currently?

**Comment by Francois-Werbrouck** [comment]
They update where they point towards their respective project.toml file?

**Comment by SonOfLope** [comment]
I will provide documentation once testing is done. I will also provide changes to both backends to refer to the packages once testing is done

**Pull request merged**
