### PR TITLE
95 update fertiscan queries module to represent updated architecture

### PR DESCRIPTION
**Pull request by Francois-Werbrouck**
ref #95 

The goal of this issue was to correct the fertiscan query modules to be updated with the current Architecture.

All FertiScan tests are passing

### CODE REVIEW

**Comment by Francois-Werbrouck** [comment]
image
All the python unittest case arer passing without any issues. I dont know what the issue is with the workflow.

**Comment by Francois-Werbrouck** [comment]
@k-allagbe all the unittests are now passing. There seem to be an error raised by the coverage, but it will be fixed in another PR for Nachet. At least the workflow is completing itself now

**Review by sylvanie85 — APPROVED** [review]
LGTM

**Pull request merged**
