### PR TITLE
176 as a dev i want company fields to be correctly persisted during analysis registration

### PR DESCRIPTION
**Pull request by Francois-Werbrouck**
This PR adds test to confirm #176 is patched

### CODE REVIEW

**Comment by Francois-Werbrouck** [comment]
@k-allagbe I advide only reviewing the last 2 commits with #176 in their title, since the rest is based on our other branch

**Comment by Francois-Werbrouck** [comment]
Ohhh it might of been done on the wrong branch. I'll rebase and add it

**Comment by Francois-Werbrouck** [comment]
> This commit seems to be missing: [e89bc9d](https://github.com/ai-cfia/ailab-datastore/commit/e89bc9d14b3be9a63dc9137b3d9d0dd6d26db9db)

This is fixed now

**Comment by k-allagbe** [comment]
The main branch is now clean. I suggest opening a new PR where only the fix would be implemented and close this one. The current one has a lot of noise that could introduce regressions or break stuff on main.

**Comment by k-allagbe** [comment]
Never mind this has already been merged. Closing this as done in #197.

**Comment by Francois-Werbrouck** [comment]
This was not merged in #197. The actual sql fix was pushed on the branch; however the tests haven't

**Comment by Francois-Werbrouck** [comment]
>the current one has a lot of noise that could introduce regressions or break stuff on main.

I should only require a rebase for it to work. I'll look into it. 
Once again, not having multiple merge and only doing a rebase on the original PR would of made this not needed 👍🏻

**Comment by Francois-Werbrouck** [comment]
Rebase is now done. There are no conflicts with main. The newly added tests are passing. This is ready for Review

**Review by k-allagbe — APPROVED** [review]

**Pull request merged**
