### PR TITLE
issue #219: testing python-lint workflow + added issue status workflow

### LINKED ISSUE #219: Run lint-test workflow on gh-runner (testing)

### PR DESCRIPTION
**Pull request by ThomasCardin**
- Closes #219

### CODE REVIEW

**Comment by ThomasCardin** [comment]
python-lint test are working on fertiscan: https://github.com/ai-cfia/fertiscan-backend/actions/runs/11941086737/job/33285161213

**Review by k-allagbe — DISMISSED** [review]

**Comment by Francois-Werbrouck** [comment]
If the workflow are running on our cluster, we need to figure why the connection to the db aint working in the workflow still

**Comment by Francois-Werbrouck** [comment]
I whitelisted the IP of our hosted GH runners. Python test are now running

**Review by Francois-Werbrouck — APPROVED** [review]
The non-passing tests are caused by another PR changes and are irrelevant to this one.

Python tests are connecting to the DB and running.

**Pull request merged**
